In [138]:
#Load the data
import pandas as pd
import sklearn

df = pd.read_csv(r"C:\Users\Lenovo\Desktop\movies_analysis\movies_prediction_data.csv")
df

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_17472\2674041256.py:5: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\Lenovo\Desktop\movies_analysis\movies_prediction_data.csv")

,release_date,runtime,budget,genres,spoken_languages,release_month,revenue
0,NaN,0,900000000,NaN,NaN,NaN,16
1,9/21/2023,115,888000000,Comedy,Italian,9,0
2,8/23/2023,5,800000000,"Horror, War",English,8,3000000000
3,9/8/2022,0,645654654,Horror,NaN,9,546546755
4,12/18/2031,0,600000000,"Action, Adventure, Science Fiction",English,12,0
...,...,...,...,...,...,...,...
1048570,2/6/2004,132,0,NaN,NaN,2,0
1048571,10/18/2006,101,0,NaN,Persian,10,0
1048572,9/7/2023,0,0,Comedy,Italian,9,0
1048573,5/18/1991,119,0,NaN,NaN,5,0
1048574,3/7/1986,120,0,NaN,Portuguese,3,0

In [136]:
#df = df.drop('release_date', axis=1)

In [143]:
#Label encoding: This method assigns a unique integer to each unique category in the string variable.
#changing genre to numeric
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['encoded_genres'] = le.fit_transform(df['genres'])
df

,release_date,runtime,budget,genres,spoken_languages,release_month,revenue,encoded_languages,encoded_genres
0,NaN,0,900000000,NaN,NaN,NaN,16,6981,13164
1,9/21/2023,115,888000000,Comedy,Italian,9,0,5222,3825
2,8/23/2023,5,800000000,"Horror, War",English,8,3000000000,1881,9481
3,9/8/2022,0,645654654,Horror,NaN,9,546546755,6981,8782
4,12/18/2031,0,600000000,"Action, Adventure, Science Fiction",English,12,0,1881,389
...,...,...,...,...,...,...,...,...,...
1048570,2/6/2004,132,0,NaN,NaN,2,0,6981,13164
1048571,10/18/2006,101,0,NaN,Persian,10,0,6124,13164
1048572,9/7/2023,0,0,Comedy,Italian,9,0,5222,3825
1048573,5/18/1991,119,0,NaN,NaN,5,0,6981,13164
1048574,3/7/1986,120,0,NaN,Portuguese,3,0,6211,13164

In [144]:
#Label encoding: This method assigns a unique integer to each unique category in the string variable.
#changing spoken_languages to numeric
df['encoded_languages'] = le.fit_transform(df['spoken_languages'])
df

,release_date,runtime,budget,genres,spoken_languages,release_month,revenue,encoded_languages,encoded_genres
0,NaN,0,900000000,NaN,NaN,NaN,16,6981,13164
1,9/21/2023,115,888000000,Comedy,Italian,9,0,5222,3825
2,8/23/2023,5,800000000,"Horror, War",English,8,3000000000,1881,9481
3,9/8/2022,0,645654654,Horror,NaN,9,546546755,6981,8782
4,12/18/2031,0,600000000,"Action, Adventure, Science Fiction",English,12,0,1881,389
...,...,...,...,...,...,...,...,...,...
1048570,2/6/2004,132,0,NaN,NaN,2,0,6981,13164
1048571,10/18/2006,101,0,NaN,Persian,10,0,6124,13164
1048572,9/7/2023,0,0,Comedy,Italian,9,0,5222,3825
1048573,5/18/1991,119,0,NaN,NaN,5,0,6981,13164
1048574,3/7/1986,120,0,NaN,Portuguese,3,0,6211,13164

In [145]:
#download the data for cleaning and inspection in excel
download = df.to_csv(r"C:\Users\Lenovo\Desktop\movies_analysis\X1.csv")

In [157]:
#import the clean data 
df1 = pd.read_csv(r"C:\Users\Lenovo\Desktop\movies_analysis\X1_clean.csv")
df1

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_17472\99266258.py:2: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv(r"C:\Users\Lenovo\Desktop\movies_analysis\X1_clean.csv")

,release_date,runtime,budget,revenue,encoded_languages,encoded_genres
0,NaN,0,900000000,16,6981,13164
1,9/21/2023,115,888000000,0,5222,3825
2,8/23/2023,5,800000000,3000000000,1881,9481
3,9/8/2022,0,645654654,546546755,6981,8782
4,12/18/2031,0,600000000,0,1881,389
...,...,...,...,...,...,...
1048570,2/6/2004,132,0,0,6981,13164
1048571,10/18/2006,101,0,0,6124,13164
1048572,9/7/2023,0,0,0,5222,3825
1048573,5/18/1991,119,0,0,6981,13164
1048574,3/7/1986,120,0,0,6211,13164

In [171]:
X = df1.drop(['revenue'], axis = 1)
#changing spoken_languages to numeric
X['encoded_dates'] = le.fit_transform(df['release_date'])
X

,release_date,runtime,budget,encoded_languages,encoded_genres,encoded_dates
0,NaN,0,900000000,6981,13164,42357
1,9/21/2023,115,888000000,5222,3825,40512
2,8/23/2023,5,800000000,1881,9481,37233
3,9/8/2022,0,645654654,6981,8782,42237
4,12/18/2031,0,600000000,1881,389,11752
...,...,...,...,...,...,...
1048570,2/6/2004,132,0,6981,13164,17679
1048571,10/18/2006,101,0,6124,13164,4685
1048572,9/7/2023,0,0,5222,3825,42125
1048573,5/18/1991,119,0,6981,13164,26135
1048574,3/7/1986,120,0,6211,13164,21292

In [172]:
#download the data for cleaning and inspection in excel
download = X.to_csv(r"C:\Users\Lenovo\Desktop\movies_analysis\X_to_clean.csv")

In [174]:
X2 = pd.read_csv(r"C:\Users\Lenovo\Desktop\movies_analysis\X_final.csv")
X2

         runtime     budget  encoded_languages  encoded_genres  encoded_dates
0              0  900000000               6981           13164          42357
1            115  888000000               5222            3825          40512
2              5  800000000               1881            9481          37233
3              0  645654654               6981            8782          42237
4              0  600000000               1881             389          11752
...          ...        ...                ...             ...            ...
1048570      132          0               6981           13164          17679
1048571      101          0               6124           13164           4685
1048572        0          0               5222            3825          42125
1048573      119          0               6981           13164          26135
1048574      120          0               6211           13164          21292

[1048575 rows x 5 columns]

In [175]:
print(X2.dtypes)

runtime              int64
budget               int64
encoded_languages    int64
encoded_genres       int64
encoded_dates        int64
dtype: object

In [181]:
# Fill null values with 0
X2.fillna(0, inplace=True)
X2

         runtime     budget  encoded_languages  encoded_genres  encoded_dates
0              0  900000000               6981           13164          42357
1            115  888000000               5222            3825          40512
2              5  800000000               1881            9481          37233
3              0  645654654               6981            8782          42237
4              0  600000000               1881             389          11752
...          ...        ...                ...             ...            ...
1048570      132          0               6981           13164          17679
1048571      101          0               6124           13164           4685
1048572        0          0               5222            3825          42125
1048573      119          0               6981           13164          26135
1048574      120          0               6211           13164          21292

[1048575 rows x 5 columns]

In [205]:
#our equation is in the form of y = f(x)
# y = revenue
#seperation of y and x as independent elements of the equation
y = df1['revenue']
# Fill null values with 0
y.fillna(0, inplace=True)
y

0                  16
1                   0
2          3000000000
3           546546755
4                   0
              ...
1048570             0
1048571             0
1048572             0
1048573             0
1048574             0
Name: revenue, Length: 1048575, dtype: object

In [218]:
y1 = pd.read_csv(r"C:\Users\Lenovo\Desktop\movies_analysis\y.csv")
y1

            revenue
0                16
1                 0
2        3000000000
3         546546755
4                 0
...             ...
1048570           0
1048571           0
1048572           0
1048573           0
1048574           0

[1048575 rows x 1 columns]

In [222]:
#Data splitting
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X2,y1, test_size = 0.2, random_state = 100)

In [223]:
X_train

         runtime  budget  encoded_languages  encoded_genres  encoded_dates
306396        60       0               1881            5485          32046
1031935       60       0               5341           13164          30563
720107         0       0               6782           13164          41539
287766        90       0               6981           13164           1929
1046033        0       0               5696           13164           9791
...          ...     ...                ...             ...            ...
864087        96       0               1881            4320           1694
778087        10       0               6322           13164          19786
210755       120       0               5491            5947          15369
56088         25       3               1881            7134          37570
824840         6       0               6981           13164          29572

[838860 rows x 5 columns]

In [224]:
X_test

        runtime   budget  encoded_languages  encoded_genres  encoded_dates
289020        0        0               5696            3924          13491
454106       73        0               1881           13164          20979
10454       170  3000000               6552            6671          32309
570172       87        0               6981           13164          42357
998286       60        0               6981           13164          33717
...         ...      ...                ...             ...            ...
858471        0        0               6981           13164          15617
529762      116        0               6729            5485           3741
452372        0        0               6981           13164          21680
463026       44        0               6552            5892          31471
61924         6        0               4270            7870          24103

[209715 rows x 5 columns]

In [225]:
#Model Building
#Linear Regression
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

#train the model
lr.fit(X_train, y_train)

LinearRegression()

In [226]:
#Applying the model to make a prediction using train data
y_lr_train_pred = lr.predict(X_train)
y_lr_train_pred

array([[214086.55134929],
       [ 11985.37574587],
       [-79708.10985828],
       ...,
       [257931.76669304],
       [123710.75090173],
       [-95651.13108281]])

In [227]:
y_lr_test_pred = lr.predict(X_test)
y_lr_test_pred

array([[  84150.84530438],
       [  31642.7966533 ],
       [7402382.96668521],
       ...,
       [-123505.95141122],
       [ 151555.47031651],
       [  31266.35327944]])

In [229]:
#Evaluate Model Perfomance
from sklearn.metrics import mean_squared_error, r2_score

lr_train_mse = mean_squared_error(y_train, y_lr_train_pred)
lr_train_r2 = r2_score(y_train, y_lr_train_pred)

lr_test_mse = mean_squared_error(y_test,y_lr_test_pred )
lr_test_r2 = r2_score(y_test, y_lr_test_pred)

In [230]:
print('LR MSE (TRAIN):', lr_train_mse)
print('LR R2 (TRAIN):', lr_train_r2)

print('LR MSE (TEST):', lr_test_mse)
print('LR R2 (TEST):', lr_test_r2)

LR MSE (TRAIN): 205350453449136.3
LR R2 (TRAIN): 0.42499294351694583
LR MSE (TEST): 168117146390693.94
LR R2 (TEST): 0.4398956546762465

In [212]:
#Random forest
from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(n_estimators=100, random_state=42)

# Train the model on the training data
rf_model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [232]:
# Make predictions on the train data
rf_y_train_pred = rf_model.predict(X_train)
rf_y_train_pred

array([0.        , 0.        , 0.        , ..., 0.        , 0.07348485,
       0.        ])

In [233]:
# Make predictions on the test data
rf_y_test_pred = rf_model.predict(X_test)
rf_y_test_pred

array([       0.  ,        0.  , 10371043.93, ...,        0.  ,
              0.  ,        0.  ])

In [234]:
#Evaluate Model Perfomance

rf_train_mse = mean_squared_error(y_train, rf_y_train_pred)
rf_train_r2 = r2_score(y_train, rf_y_train_pred)

rf_test_mse = mean_squared_error(y_test, rf_y_test_pred)
rf_test_r2 = r2_score(y_test, rf_y_test_pred)

In [235]:
print('RF MSE (TRAIN):', rf_train_mse)
print('RF R2 (TRAIN):', rf_train_r2)

print('RF MSE (TEST):', rf_test_mse)
print('RF R2 (TEST):', rf_test_r2)

RF MSE (TRAIN): 30449144804505.527
RF R2 (TRAIN): 0.9147385709045843
RF MSE (TEST): 160326026428445.34
RF R2 (TEST): 0.46585279372768373

In [236]:
rf_results = pd.DataFrame(['Random Forest', rf_train_mse, rf_train_r2, rf_test_mse, rf_test_r2]).transpose()
rf_results.columns = ['Method', 'Training MSE', 'Training R2', 'Test MSE', 'Test R2']
rf_results

,Method,Training MSE,Training R2,Test MSE,Test R2
0,Random Forest,30449144804505.527344,0.914739,160326026428445.34375,0.465853

In [237]:
lr_results = pd.DataFrame(['Linear Regression', lr_train_mse, lr_train_r2, lr_test_mse, lr_test_r2]).transpose()
lr_results.columns = ['Method', 'Training MSE', 'Training R2', 'Test MSE', 'Test R2']
lr_results

,Method,Training MSE,Training R2,Test MSE,Test R2
0,Linear Regression,205350453449136.3125,0.424993,168117146390693.9375,0.439896

In [238]:
#Combining the 2 tables
df_models = pd.concat([lr_results, rf_results], axis = 0)
df_models

,Method,Training MSE,Training R2,Test MSE,Test R2
0,Linear Regression,205350453449136.3125,0.424993,168117146390693.9375,0.439896
0,Random Forest,30449144804505.527344,0.914739,160326026428445.34375,0.465853